name: Publish NPM Module
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  unit-tests:
    uses: ./.github/workflows/_test.yml
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: unit-tests
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm install
      - run: npx tsdx build --entry index.ts
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release